import eventBus from './eventBus.js';
import PurchaseOrder from '../models/PurchaseOrder.js';
import Vendor from '../models/Vendor.js';
import Warehouse from '../models/Warehouse.js';
import Product from '../models/Product.js';

export const handleLowStockDeduction = async (data) => {
  try {
    const { productId, title, newStock, reorderPoint, reorderQuantity, preferredVendor, unitCost } = data;

    if (newStock > (reorderPoint ?? 5)) return null;

    // Deduplication check: check if a draft PO already contains this product
    const existingDraft = await PurchaseOrder.findOne({
      status: 'draft',
      'items.product': productId
    });

    if (existingDraft) {
      console.log(`[SCM Service] Draft PO ${existingDraft.poNumber} already exists for product "${title}". Skipping duplicate auto-generation.`);
      return existingDraft;
    }

    // Resolve Vendor
    let vendorId = preferredVendor;
    if (!vendorId) {
      const activeVendor = await Vendor.findOne({ status: 'active' });
      if (activeVendor) {
        vendorId = activeVendor._id;
      } else {
        // Create a default system vendor if none exists
        const defaultVendor = new Vendor({
          vendorCode: 'VEN-SYS-DEFAULT',
          name: 'Primary System Supplier',
          contactName: 'Procurement Dept',
          email: 'procurement@centstore.com',
          phone: '+254700000000',
          status: 'active'
        });
        await defaultVendor.save();
        vendorId = defaultVendor._id;
      }
    }

    // Resolve Warehouse
    let defaultWarehouse = await Warehouse.findOne({ isDefault: true }) || await Warehouse.findOne({ status: 'active' });
    if (!defaultWarehouse) {
      // Create default central warehouse if none exists
      defaultWarehouse = new Warehouse({
        code: 'WH-NRB-MAIN',
        name: 'Nairobi Central Warehouse',
        location: { city: 'Nairobi', country: 'Kenya', address: 'Central Hub' },
        capacity: 10000,
        isDefault: true,
        status: 'active'
      });
      await defaultWarehouse.save();
    }

    const qty = reorderQuantity || 20;
    const cost = unitCost || 100;
    const subtotal = qty * cost;
    const poNumber = `PO-AUTO-${Date.now().toString().slice(-6)}`;

    const draftPo = new PurchaseOrder({
      poNumber,
      vendor: vendorId,
      warehouse: defaultWarehouse._id,
      items: [{
        product: productId,
        productTitle: title || 'Low Stock Product',
        quantityOrdered: qty,
        quantityReceived: 0,
        unitCost: cost,
        subtotal
      }],
      subtotalAmount: subtotal,
      taxAmount: 0,
      totalAmount: subtotal,
      status: 'draft',
      isAutoGenerated: true,
      notes: `Automated draft PO triggered by low stock alert (Current stock: ${newStock}, Reorder point: ${reorderPoint ?? 5}).`
    });

    const savedPo = await draftPo.save();
    console.log(`[SCM Service] Successfully generated auto draft PO ${poNumber} for product "${title}".`);
    return savedPo;
  } catch (err) {
    console.error('[SCM Service Error] Failed to handle low stock deduction:', err);
    return null;
  }
};

export const initScmEventListeners = () => {
  eventBus.on('stock:deducted', async (data) => {
    await handleLowStockDeduction(data);
  });
  console.log('[SCM Service] Initialized SCM Event Listeners on eventBus.');
};

export const triggerLowStockDraftPOForProduct = async (productId) => {
  const product = await Product.findById(productId);
  if (!product) throw new Error(`Product ${productId} not found`);
  return await handleLowStockDeduction({
    productId: product._id,
    title: product.title || product.name,
    newStock: product.stock,
    reorderPoint: product.reorderPoint ?? 5,
    reorderQuantity: product.reorderQuantity ?? 20,
    preferredVendor: product.preferredVendor,
    unitCost: Math.round(product.price * 0.6)
  });
};
