import mongoose, { Schema } from 'mongoose';

const purchaseOrderItemSchema = new Schema({
  product: {
    type: Schema.Types.ObjectId,
    ref: 'Product',
    required: true
  },
  productTitle: { type: String, required: true },
  quantityOrdered: { type: Number, required: true, min: 1 },
  quantityReceived: { type: Number, default: 0, min: 0 },
  unitCost: { type: Number, required: true, min: 0 },
  subtotal: { type: Number, required: true, min: 0 }
}, { _id: true });

const purchaseOrderSchema = new Schema({
  poNumber: {
    type: String,
    required: true,
    unique: true,
    uppercase: true,
    trim: true
  },
  vendor: {
    type: Schema.Types.ObjectId,
    ref: 'Vendor',
    required: true
  },
  warehouse: {
    type: Schema.Types.ObjectId,
    ref: 'Warehouse',
    required: true
  },
  items: [purchaseOrderItemSchema],
  subtotalAmount: { type: Number, required: true, default: 0 },
  taxAmount: { type: Number, default: 0 },
  totalAmount: { type: Number, required: true, default: 0 },
  status: {
    type: String,
    enum: ['draft', 'ordered', 'received', 'cancelled'],
    default: 'draft'
  },
  isAutoGenerated: { type: Boolean, default: false },
  notes: { type: String, default: '' },
  createdBy: {
    type: Schema.Types.ObjectId,
    ref: 'Staff',
    required: false
  },
  expectedDeliveryDate: { type: Date },
  receivedAt: { type: Date },
  apInvoiceCreated: { type: Boolean, default: false }
}, {
  timestamps: true
});

purchaseOrderSchema.index({ vendor: 1 });
purchaseOrderSchema.index({ warehouse: 1 });
purchaseOrderSchema.index({ status: 1 });

const PurchaseOrder = mongoose.model('PurchaseOrder', purchaseOrderSchema);
export default PurchaseOrder;
